name = "LinearOperators"
uuid = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
version = "2.11.0"

[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
FastClosures = "9aa1b823-49e4-5ca5-8b0f-3971ec8bab6a"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
TSVD = "9449cd9e-2762-5aa3-a617-5413e99d722e"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[weakdeps]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
JLArrays = "27aeb0d3-9eb9-45fb-866b-73c2ecf80fcb"
LDLFactorizations = "40e66cde-538c-5869-a4ad-c39174c6795b"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"

[extensions]
LinearOperatorsAMDGPUExt = "AMDGPU"
LinearOperatorsCUDAExt = "CUDA"
LinearOperatorsChainRulesCoreExt = "ChainRulesCore"
LinearOperatorsJLArraysExt = "JLArrays"
LinearOperatorsLDLFactorizationsExt = "LDLFactorizations"
LinearOperatorsMetalExt = "Metal"

[compat]
AMDGPU = "2"
Arpack = "0.5.4"
CUDA = "5"
ChainRulesCore = "1"
FastClosures = "0.2, 0.3"
GenericLinearAlgebra = "0.3.18"
JLArrays = "0.1, 0.2"
LDLFactorizations = "0.9, 0.10"
LinearAlgebra = "1"
Metal = "1.1"
Printf = "1"
Requires = "1"
SparseArrays = "1"
TSVD = "0.4.4"
TimerOutputs = "^0.5"
julia = "^1.6.0"

[extras]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
JLArrays = "27aeb0d3-9eb9-45fb-866b-73c2ecf80fcb"
LDLFactorizations = "40e66cde-538c-5869-a4ad-c39174c6795b"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
